INSERT INTO PRODUCT (PRODUCTID, PRODUCT_NAME, PRODUCT_DESC, PRODUCT_BRAND, PRODUCT_PRICE, PRODUCT_CATEGORY, PRODUCT_RELEASE_DATE, PRODUCT_AVAILABLE, PRODUCT_QUANTITY)
VALUES (1, 'Galaxy S24 Ultra', 'Flagship smartphone with 200MP camera', 'Samsung', 129999.00, 'Electronics', '2024-02-10', TRUE, 50);

INSERT INTO PRODUCT (PRODUCTID, PRODUCT_NAME, PRODUCT_DESC, PRODUCT_BRAND, PRODUCT_PRICE, PRODUCT_CATEGORY, PRODUCT_RELEASE_DATE, PRODUCT_AVAILABLE, PRODUCT_QUANTITY)
VALUES (2, 'MacBook Pro M3', 'High-performance laptop for professionals', 'Apple', 189999.00, 'Electronics', '2024-03-15', TRUE, 30);

INSERT INTO PRODUCT (PRODUCTID, PRODUCT_NAME, PRODUCT_DESC, PRODUCT_BRAND, PRODUCT_PRICE, PRODUCT_CATEGORY, PRODUCT_RELEASE_DATE, PRODUCT_AVAILABLE, PRODUCT_QUANTITY)
VALUES (3, 'Sony WH-1000XM5', 'Noise-canceling over-ear headphones', 'Sony', 29999.00, 'Accessories', '2023-11-20', TRUE, 100);

INSERT INTO PRODUCT (PRODUCTID, PRODUCT_NAME, PRODUCT_DESC, PRODUCT_BRAND, PRODUCT_PRICE, PRODUCT_CATEGORY, PRODUCT_RELEASE_DATE, PRODUCT_AVAILABLE, PRODUCT_QUANTITY)
VALUES (4, 'Nike Air Max 270', 'Comfortable running shoes', 'Nike', 11999.00, 'Fashion', '2022-08-01', TRUE, 200);

INSERT INTO PRODUCT (PRODUCTID, PRODUCT_NAME, PRODUCT_DESC, PRODUCT_BRAND, PRODUCT_PRICE, PRODUCT_CATEGORY, PRODUCT_RELEASE_DATE, PRODUCT_AVAILABLE, PRODUCT_QUANTITY)
VALUES (5, 'The Psychology of Money', 'Book on financial behavior', 'Morgan Housel', 499.00, 'Books', '2020-09-01', TRUE, 150);

INSERT INTO PRODUCT (PRODUCTID, PRODUCT_NAME, PRODUCT_DESC, PRODUCT_BRAND, PRODUCT_PRICE, PRODUCT_CATEGORY, PRODUCT_RELEASE_DATE, PRODUCT_AVAILABLE, PRODUCT_QUANTITY)
VALUES (6, 'iPad Air 2024', 'Lightweight tablet with M2 chip', 'Apple', 74999.00, 'Electronics', '2024-04-05', TRUE, 25);

INSERT INTO PRODUCT (PRODUCTID, PRODUCT_NAME, PRODUCT_DESC, PRODUCT_BRAND, PRODUCT_PRICE, PRODUCT_CATEGORY, PRODUCT_RELEASE_DATE, PRODUCT_AVAILABLE, PRODUCT_QUANTITY)
VALUES (7, 'Canon EOS R10', 'Mirrorless camera for creators', 'Canon', 85999.00, 'Photography', '2023-10-10', TRUE, 15);

INSERT INTO PRODUCT (PRODUCTID, PRODUCT_NAME, PRODUCT_DESC, PRODUCT_BRAND, PRODUCT_PRICE, PRODUCT_CATEGORY, PRODUCT_RELEASE_DATE, PRODUCT_AVAILABLE, PRODUCT_QUANTITY)
VALUES (8, 'Adidas Ultraboost', 'Premium running shoes with Boost tech', 'Adidas', 13999.00, 'Fashion', '2022-05-20', TRUE, 120);

INSERT INTO PRODUCT (PRODUCTID, PRODUCT_NAME, PRODUCT_DESC, PRODUCT_BRAND, PRODUCT_PRICE, PRODUCT_CATEGORY, PRODUCT_RELEASE_DATE, PRODUCT_AVAILABLE, PRODUCT_QUANTITY)
VALUES (9, 'Atomic Habits', 'Book on building good habits and breaking bad ones', 'James Clear', 599.00, 'Books', '2018-10-16', TRUE, 180);

INSERT INTO PRODUCT (PRODUCTID, PRODUCT_NAME, PRODUCT_DESC, PRODUCT_BRAND, PRODUCT_PRICE, PRODUCT_CATEGORY, PRODUCT_RELEASE_DATE, PRODUCT_AVAILABLE, PRODUCT_QUANTITY)
VALUES (10, 'Logitech MX Master 3S', 'Ergonomic wireless mouse', 'Logitech', 8999.00, 'Accessories', '2022-12-12', TRUE, 60);
